export const HELP_TEXT = {
  loading: "Судалгааг ачааллаж байна…",
  alreadyTakenSuffix: "Та энэ судалгааг өмнө нь бөглөсөн байна. Баярлалаа!",
  unavailableFallback: "Энэ судалгаа одоогоор оролцох боломжгүй байна.",
  titleFallback: "Судалгаанд оролцох",
  creatorLabel: "Судалгаа нийтлэгч: ",
  startButton: "Эхлэх",
  continueButton: "Цааш",
  startingButton: "Ачаалж байна…",
  consentCheckboxLabel: "Зөвшөөрлийн хуудастай танилцсан болно.",
  passcodeLegend: "Нэвтрэх код",
  questionsCountSuffix: "асуулт",
  minutesRangeSeparator: "-",
  minutesSuffix: "минут",
  unknownRangeValue: "?",
  multiChoiceHintPrefix: "Доод тал нь",
  multiChoiceHintMid: "хариулт, дээд тал нь",
  multiChoiceHintSuffix: "хариулт сонгоно уу.",
  textInputPlaceholder: "Хариулт оруулна уу",
  dropdownPlaceholder: "Сонгох",
  optionalHint: "*Алгасах боломжтой",
  conditionalHint: "*Өмнөх асуултуудын хариулт дээр үндэслэн хариулах шаардлагагүй",
};
